name: flutter_fps
description: A Flutter library to catch fps.
version: 0.0.1
author: chenenyu <ceychina@gmail.com>
homepage: https://github.com/chenenyu/flutter-fps

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
